services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        fromService:
          type: pserv
          name: laravel-mysql
          property: host
      - key: DB_DATABASE
        value: mytodolist
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: laravel-mysql
          property: password

  - type: pserv
    name: laravel-mysql
    env: docker          #THIS is the fix
    plan: free
    image: mysql:8.0    
    envVars:
      - key: MYSQL_DATABASE
        value: mytodolist
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1

